input {
  http {
    port => 8080
    host => "0.0.0.0"
    codec => "plain"
  }
}

filter {
  # Parse JSON
  json {
    source => "message"
    target => "parsed_data"
    skip_on_invalid_json => true
  }
  
  # Handle array case
  if [parsed_data] {
    ruby {
      code => '
        data = event.get("parsed_data")
        
        if data.is_a?(Array) && data.length > 0
          first_item = data[0]
          if first_item.is_a?(Hash)
            first_item.each do |key, value|
              event.set(key, value)
            end
          end
        elsif data.is_a?(Hash)
          data.each do |key, value|
            event.set(key, value)
          end
        end
        
        event.remove("parsed_data")
      '
    }
  }
  fingerprint {
    source => ["log_timestamp", "source_file", "MessageTemplate", "app_id", "app_name"]
    target => "[@metadata][fingerprint]"
    method => "SHA256"
    concatenate_sources => true
  }
  # Make unique ID
  fingerprint {
    source => ["log_timestamp", "source_file", "app_properties", "app_id", "app_name"]
    target => "[@metadata][fingerprint]"
    method => "SHA256"
    concatenate_sources => true
  }
  
  # Extract specific fields from Properties
  if [Properties] {
    if [Properties][ApplicationId] {
      mutate {
        add_field => { "app_id" => "%{[Properties][ApplicationId]}" }
      }
    }
    if [Properties][ApplicationName] {
      mutate {
        add_field => { "app_name" => "%{[Properties][ApplicationName]}" }
      }
    }
    # Keep Properties as app_properties
    mutate {
      add_field => { "app_properties" => "%{Properties}" }
    }
  }
  
  # Basic field mapping
  if [Level] {
    mutate { rename => { "Level" => "log_level" } }
  }
  if [MessageTemplate] {
    mutate { rename => { "MessageTemplate" => "log_message" } }
  }
  if [Timestamp] {
    date {
      match => [ "Timestamp", "ISO8601" ]
      target => "@timestamp"
    }
    mutate { rename => { "Timestamp" => "log_timestamp" } }
  }
  
  mutate {
  remove_field => ["event.original"]
  }
  # Metadata
  mutate {
    add_field => { 
      "received_at" => "%{@timestamp}"
      "processed_by" => "logstash"
    }
    remove_field => [ "message", "headers", "host", "Properties" ]
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "serilog-logs-%{+YYYY.MM.dd}"
    # for not duplicate
    document_id => "%{[@metadata][fingerprint]}"
    # Template management
    template_name => "serilog_template"
    template => "/etc/logstash/templates/serilog-template.json"
    template_overwrite => true
  }
  stdout {
    codec => rubydebug { metadata => false }
  }
}