services:
  elk:
    image: sebp/elk:latest
    ports:
      - "5601:5601"   # Kibana
      - "9200:9200"   # Elasticsearch
      - "5044:5044"   # Logstash Beats input
      - "5000:5000"   # Logstash TCP input
      - "8080:8080"   # Logstash HTTP input
    environment:
      - MAX_MAP_COUNT=262144
      - ES_MIN_MEM=512m
      - ES_MAX_MEM=2g
      - LS_MIN_MEM=512m
      - LS_MAX_MEM=2g
    volumes:
      - elk_data:/var/lib/elasticsearch
      - .\docker\logstash-http.conf:/etc/logstash/conf.d/30-http-input.conf:ro
    ulimits:
      memlock:
        soft: -1
        hard: -1

  myconsoleapp:
      image: myapp:latest
      ports:
      - "9090:9090"   # prometeus
      - "8686:8686"   # vector api
      volumes:
      - D:\logs\:/var/log/app/
      - D:\vector\:/var/lib/vector
volumes:
  elk_data:
    driver: local