<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SerilogLogger.Abstraction\SerilogLogger.Abstraction.csproj" />
		<ProjectReference Include="..\SerilogLogger.Utilities\SerilogLogger.Utilities.csproj" />
		<ProjectReference Include="..\SerilogLogger\SerilogLogger.Implementation.csproj" />
	</ItemGroup>

</Project>