  <Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
      <TargetFramework>net8.0</TargetFramework>
      <Nullable>enable</Nullable>
      <ImplicitUsings>enable</ImplicitUsings>
      <AssemblyTitle>SerilogLogger Test</AssemblyTitle>
      <AssemblyDescription>Test application for SerilogLogger</AssemblyDescription>
      <AssemblyVersion>2.0.0</AssemblyVersion>
      <FileVersion>2.0.0</FileVersion>
      <Version>2.0.0</Version>
    </PropertyGroup>

    <ItemGroup>
      <!-- Web App Dependencies -->
      <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.3" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.8" />
      <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.8" />

    </ItemGroup>

    <ItemGroup>
      <!-- SerilogLogger NuGet Package - Complete solution -->
      <PackageReference Include="SerilogLogger.Utilities" Version="2.0.0" />
      <!-- یا می‌تونید فقط implementation استفاده کنید اگر utilities لازم ندارید -->
       <PackageReference Include="SerilogLogger.Implementation" Version="2.0.0" /> 
    </ItemGroup>
  </Project>