<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<PackageId>SerilogLogger</PackageId>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>10.0</LangVersion>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	</PropertyGroup>

</Project>
