<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>netstandard2.1</TargetFramework>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>enable</Nullable>
	  <LangVersion>10.0</LangVersion>
	  <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	  <AssemblyVersion>1.0.1</AssemblyVersion>
	  <FileVersion>1.0.1</FileVersion>
	  <Version>1.0.1</Version>
	  <Description>
		  1-Remove Some utiliteis UnionKeyValuPair that has bugs.
	  </Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.0" />
  </ItemGroup>

</Project>
